358 error next prev page
hugo-toha/toha pull request #359
Opened 2021-06-17 20:09 UTC by jbleduigou

### Issue
https://github.com/hugo-toha/toha/issues/358

### Description

Init an empty slice in case the site config has no menus.

2021-06-18 03:55 UTC, hossainemruz requested changes
@jbleduigou Thank you for the PR. I have added a comment. Can you please acknowledge it.

2021-06-18 03:55 UTC, hossainemruz commented on layouts/partials/navigators/next-prev-navigator.html
> +  {{ $pages := partial "helpers/get-pages.html" site.Menus.sidebar }}
Use `=` instead of `:=` here.
```
{{ $pages := partial "helpers/get-pages.html" site.Menus.sidebar }}
```

2021-06-18 19:01 UTC, jbleduigou commented on layouts/partials/navigators/next-prev-navigator.html
> +  {{ $pages := partial "helpers/get-pages.html" site.Menus.sidebar }}
Good catch!

2021-06-19 19:10 UTC, hossainemruz approved these changes

2021-06-19 19:12 UTC, merged