add giscus
hugo-toha/toha pull request #543
Opened 2022-02-28 06:45 UTC by Rihoj

### Issue
#536 

### Description
Adds [Giscus](https://giscus.app/) support
I do think a guide post should be added, but I wanted to make sure you like how this is done before I start writing out a post. (Unless someone else wants to write it)

### Test Evidence
![image](https://user-images.githubusercontent.com/1520296/155936581-895fcef1-d566-4857-8b2b-9e27e207a322.png)

2022-02-28 07:29 UTC, hossainemruz requested changes
Thank you @Rihoj. Looks good to me. Just a little change. Can you please acknowledge the comments?

2022-02-28 07:29 UTC, hossainemruz commented on layouts/partials/giscus.html
> +{{ $category := site.Params.features.comment.giscus.category | default "Announcements" }}
Let's use `General`

2022-02-28 07:29 UTC, hossainemruz commented on layouts/partials/giscus.html
> +{{ $theme := site.Params.features.comment.giscus.theme | default "dark" }}
Please use `light` theme by default.

2022-02-28 17:36 UTC, hossainemruz approved these changes

2022-02-28 17:37 UTC, hossainemruz commented
Thank you @Rihoj . Looks good to me. Would you like to have a PR in guide repo? I can merge this PR.

2022-02-28 17:39 UTC, Rihoj commented
@hossainemruz I am currently working on the guide PR. Since the structure was a single page for Analytics and Comments, I am working on detailing the whole page out, so it will be a little longer as I am not always elegant with my words.

2022-02-28 17:44 UTC, hossainemruz commented
Yes. It will be good idea to separate the analytics and comment post.

2022-02-28 17:45 UTC, merged

2023-03-11 02:25 UTC, roumail commented
I'm unable to see comments on my website following these instructions for giscus. Any ideas what could have gone wrong?

2023-03-11 02:38 UTC, roumail commented
Switched to utteranc and it still doesn't work...