Bundling JS with ESBuild
hugo-toha/toha pull request #702
Opened 2022-11-12 02:03 UTC by aq1018

## Issue

In [Better Lighthouse Scores](https://github.com/hugo-toha/toha/discussions/697) Discussion, I agreed to bundle JS and CSS. This PR accomplishes the JS part.

@hossainemruz, I had the goal of changing as little as possible while accomplishing the conversion, however, due to es6 module not allowing to write to globals, I had to refactor quite a bit of code. So, sorry if there are a lot of changes.

I tested this PR as much as I could, and I couldn't find any issues. But given the amount of changes, I won't be surprised if there are bugs / regressions. Just pin me, and I'll address them in this PR.

Also, the `config.yml` file format has changed a bit. Specifically, I added a lot of switches to enable / disable certain features to allow treeshaking of unused js code. I'll comment about the details in tomorrow. ( Took me too long and I'll write up an explanation tomorrow. )

2022-11-12 11:55 UTC, hossainemruz commented
Hi @aq1018, Thank you for your hard work in this PR. Look like lot of changes. I might take some time to finish reviewing. Feel free to work on CSS PR based on this branch. Once, this PR get merged, we can rebase the CSS PR against main branch.

2022-11-12 19:13 UTC, aq1018 commented
That's the plan! 😄

2022-11-14 05:08 UTC, aq1018 commented
Hi @hossainemruz I realized that I made a few mistakes on achievements and some other feature toggle related conditionals, I added two more small commits to fix those issues.

P.s. I added  an example`config.yml` to reflect updated settings. When testing, you should use that one as a basis.

2022-11-14 05:37 UTC, hossainemruz commented
Okay. This is major change. It may break backward compatibility for existing users. I think we should bump a major version with this change. Feel free to make your changes. Do whatever best for the theme.

2022-11-14 05:59 UTC, aq1018 commented
Found video-player shortcode wasn't working. fixed.

2022-11-14 06:02 UTC, aq1018 commented
@hossainemruz p.s. I updated the `config.yaml` file in top comment. I missed a few flags.

2022-11-15 22:24 UTC, aq1018 commented
@hossainemruz This PR is ready for review. As well as the CSS bundle #705 
Let me know if you need me to change anything. Thanks!

2022-11-16 16:18 UTC, hossainemruz commented
Thank you @aq1018. I have released a new version of the theme with latest changes. This paves the way to merge these PRs. I have started reviewing. It may take few days though.

2022-12-28 20:11 UTC, hossainemruz commented
Hi @aq1018 Can you give me permission to push in this PR?

2022-12-28 20:47 UTC, hossainemruz requested changes
Hi @aq1018, My apologies for this late review. I was on deadline for another project. Then, there was FIFA world cup :P.  Now, I am able to spend some time with this project. Let's get it merge.

Regarding the PR. Thank you for this immense amount of work. The project is now better organized and will be easy to work with.

The PR looks good to me. There are few comments. Mostly related to use of deprecated function. Can you please take a look.

2022-12-28 20:47 UTC, hossainemruz commented on assets/scripts/features/darkmode/index.js
> +  throw Error(' No service defined for feature markMode.');
Possible typo. Change `markMode` to `darkMode`.

2022-12-28 20:47 UTC, hossainemruz commented on assets/scripts/pages/note.js
> +$(document).ready(function () {
`ready()` function seems to be deprecated. Can we move to the alternative?

2022-12-28 20:47 UTC, hossainemruz commented on assets/scripts/pages/single.js
> +  $(window).scroll(function () {
`scroll()` function has been deprecated. Can we move to alternative?

2022-12-28 20:47 UTC, hossainemruz commented on assets/scripts/sections/navbar.js
> +$(document).ready(function () {
`ready()` is deprecated. Let's move on alternative.

2022-12-28 20:47 UTC, hossainemruz commented on assets/scripts/sections/navbar.js
> +  $(document).scroll(function () {
`scroll()` deprecated.

2022-12-29 21:55 UTC, aq1018 commented
@hossainemruz thanks for the review. I'll work on it later today.

2023-01-05 02:28 UTC, aq1018 commented
@ hossainemruz sorry for the long wait. I ended up doing the following:

1. installed eslint and configured it to use the `standard` + `prettier` + `no-jquery` config.
2. use that to find errors in code ( had a few missing `const`s, and some minor issues )
3. migrated away from jquery with the `eslint-config-no-jquery`'s help.
4. formatted code with eslint to have a consistent js code style.
5. rebased to latest main.

I hope you don't mind me adding the [standard](https://standardjs.com/index.html#why-should-i-use-javascript-standard-style) style guide. If you don't like `standard`, there is also other popular style guides such as `airbnb`, `google` or other standards. For more details please see this article: https://betterprogramming.pub/comparing-the-top-three-style-guides-and-setting-them-up-with-eslint-98ea0d2fc5b7

Lastly, I still haven't had the chance to test it against the example site yet. I will do more testing tomorrow.

2023-01-05 18:41 UTC, hossainemruz approved these changes
The PR looks good to me. Thank you again for this immense amount of work. 💘

2023-01-05 18:42 UTC, merged